name: Build and Release Mod

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Download SMAPI
        run: |
          Invoke-WebRequest -Uri "https://github.com/Pathoschild/SMAPI/releases/download/4.2.1/SMAPI-4.2.1-installer.zip" -OutFile "smapi.zip"
          Expand-Archive smapi.zip -DestinationPath smapi
          New-Item -ItemType Directory -Path smapi-libs -Force
        shell: pwsh

      - name: Build & zip
        shell: pwsh
        run: |
          dotnet clean
          dotnet build `
            --configuration Release `
            -p:GamePath="C:\Program Files\Steam\steamapps\common\Stardew Valley"


      - name: Package mod ZIP
        run: |
          $ErrorActionPreference = 'Stop'
          $modName   = 'AlonsMOTD'
          $outputDir = "${{github.workspace}}\bin\Release\net7.0"
          $zipPath   = "${{github.workspace}}\${modName}.zip"

          # Copy only the files we need into the output folder
          Copy-Item -Path 'AlonsMOTD.dll','manifest.json','README.md','LICENSE.txt' -Destination $outputDir -Force

          # (Optional) include assets screenshots
          # Copy-Item -Path 'assets\*' -Destination "$outputDir\assets" -Recurse -Force

          Compress-Archive -Path "$outputDir\*" -DestinationPath $zipPath -Force
        shell: pwsh

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/Release/net7.0/AlonsMOTD.dll
            AlonsMOTD.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
