name: Build and Release Mod

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      # 1) Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Setup .NET 7
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      # 3) Restore and build
      - name: Restore & build
        run: |
          dotnet clean
          dotnet restore
          dotnet build --configuration Release
        shell: pwsh

      # 4) Package mod DLL, manifest, config, docs into a zip
      - name: Package mod ZIP
        run: |
          $modName = 'AlonsMOTD'
          $binDir  = "$env:GITHUB_WORKSPACE\bin\Release\net7.0"
          $zipPath = "$env:GITHUB_WORKSPACE\${modName}.zip"

          # ensure output folder exists
          New-Item -ItemType Directory -Path $binDir -Force

          # copy the built DLL and support files
          Copy-Item -Path `
            "$env:GITHUB_WORKSPACE\bin\Release\net7.0\AlonsMOTD.dll", `
            "$env:GITHUB_WORKSPACE\manifest.json", `
            "$env:GITHUB_WORKSPACE\config.json", `
            "$env:GITHUB_WORKSPACE\README.md", `
            "$env:GITHUB_WORKSPACE\LICENSE.txt" `
            -Destination $binDir -Force

          Compress-Archive -Path "$binDir\*" -DestinationPath $zipPath -Force
        shell: pwsh

      # 5) Upload DLL and ZIP as release assets
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/Release/net7.0/AlonsMOTD.dll
            AlonsMOTD.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
